[time]
disabled = false
format = 'ğŸ•™[\[ $time \]]($style) '
time_format = "%T"
utc_time_offset = "-5"
time_range = "10:00:00-14:00:00"


[character]
success_symbol = "[ğŸºğŸš€ â‡ ](bold green)"
error_symbol   = "[â˜ ï¸ ğŸš€ â‡ ](bold red)"

[directory]
truncation_length = 1
truncate_to_repo = true
truncation_symbol = "ğŸ‘½ğŸ—  "
